spring.application.name=gateway
server.port=7979

# a gauge metric for number of RouteDefinitions
spring.cloud.gateway.server.webflux.metrics.enabled=true
logging.level.org.springframework.web=info

# actuator config
management.endpoints.web.exposure.include=prometheus,health,info
management.prometheus.metrics.export.enabled=true
spring.cloud.gateway.server.webflux.metrics.path-tags.enabled=true
management.metrics.tags.application=${spring.application.name}

# Trace config
management.tracing.export.enabled=true
management.tracing.export.otlp.enabled=true
management.opentelemetry.tracing.export.otlp.transport=grpc
management.opentelemetry.logging.export.otlp.transport=grpc
# export logs to otel-collector service
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4317/v1/logs
# export spans to otel-collector service
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4317/v1/traces
# 100% for local testing; lower this in prod (e.g. 0.1)
management.tracing.sampling.probability=1.0